.TH "D:/Coding/EasyEngine/src/Algorithm.h" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/EasyEngine/src/Algorithm.h \- 算法库  

.SH SYNOPSIS
.br
.PP
\fR#include 'Basic\&.h'\fP
.br
\fR#include 'Components\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBEasyEngine::Algorithm\fP"
.br
.RI "算法库 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBEasyEngine\fP"
.br
.RI "引擎 "
.in -1c
.SH "详细描述"
.PP 
算法库 

提供图形绘制相关的算法实现，为渲染提供计算支持。

.PP
\fB版权所有\fP
.RS 4
Copyright © 2025 CatIsNotFound 
.RE
.PP
\fB作者\fP
.RS 4
CatIsNotFound 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
