.TH "D:/Coding/EasyEngine/src/Components.h" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/EasyEngine/src/Components.h \- 组件库  

.SH SYNOPSIS
.br
.PP
\fR#include 'Basic\&.h'\fP
.br
\fR#include 'Core\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBEasyEngine::Components::BGM\fP"
.br
.RI "背景音乐 "
.ti -1c
.RI "class \fBEasyEngine::Components::SFX\fP"
.br
.RI "音效 "
.ti -1c
.RI "class \fBEasyEngine::Components::Timer\fP"
.br
.RI "定时器 "
.ti -1c
.RI "class \fBEasyEngine::Components::FrameTimer\fP"
.br
.RI "计帧器 "
.ti -1c
.RI "class \fBEasyEngine::Components::Sprite\fP"
.br
.RI "精灵 "
.ti -1c
.RI "struct \fBEasyEngine::Components::Sprite::Properties\fP"
.br
.RI "绘制属性（仅用于 Spirit 绘制） "
.ti -1c
.RI "class \fBEasyEngine::Components::SpriteGroup\fP"
.br
.RI "精灵组合 "
.ti -1c
.RI "class \fBEasyEngine::Components::Animation\fP"
.br
.ti -1c
.RI "class \fBEasyEngine::Components::Collider\fP"
.br
.ti -1c
.RI "class \fBEasyEngine::Components::Entity\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBEasyEngine\fP"
.br
.RI "引擎 "
.ti -1c
.RI "namespace \fBComponents\fP"
.br
.RI "组件库 "
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "using \fBSSurface\fP = SDL_Surface"
.br
.ti -1c
.RI "using \fBSTexture\fP = SDL_Texture"
.br
.ti -1c
.RI "using \fBSRenderer\fP = SDL_Renderer"
.br
.ti -1c
.RI "using \fBSFRect\fP = SDL_FRect"
.br
.ti -1c
.RI "using \fBSRect\fP = SDL_Rect"
.br
.in -1c
.SH "详细描述"
.PP 
组件库 

定义引擎下使用到的所有组件，包含：精灵、动画、对象、碰撞体等

.PP
\fB版权所有\fP
.RS 4
Copyright © 2025 CatIsNotFound 
.RE
.PP
\fB作者\fP
.RS 4
CatIsNotFound 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
