.TH "D:/Coding/EasyEngine/src/Components.h" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/EasyEngine/src/Components.h \- 组件库  

.SH SYNOPSIS
.br
.PP
\fR#include 'Basic\&.h'\fP
.br
\fR#include 'Core\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBEasyEngine::Components::BGM\fP"
.br
.RI "背景音乐 "
.ti -1c
.RI "class \fBEasyEngine::Components::SFX\fP"
.br
.RI "音效 "
.ti -1c
.RI "class \fBEasyEngine::Components::Timer\fP"
.br
.RI "定时器 "
.ti -1c
.RI "class \fBEasyEngine::Components::Trigger\fP"
.br
.RI "触发器 "
.ti -1c
.RI "class \fBEasyEngine::Components::Sprite\fP"
.br
.RI "精灵 "
.ti -1c
.RI "struct \fBEasyEngine::Components::Sprite::Properties\fP"
.br
.RI "绘制属性（仅用于 Spirit 绘制） "
.ti -1c
.RI "class \fBEasyEngine::Components::SpriteGroup\fP"
.br
.RI "精灵组合 "
.ti -1c
.RI "class \fBEasyEngine::Components::FrameAnimation\fP"
.br
.RI "帧动画 "
.ti -1c
.RI "class \fBEasyEngine::Components::Element\fP"
.br
.RI "存储元素 "
.ti -1c
.RI "class \fBEasyEngine::Components::Collider\fP"
.br
.RI "碰撞器 "
.ti -1c
.RI "union \fBEasyEngine::Components::Collider::Container::Shape\fP"
.br
.ti -1c
.RI "class \fBEasyEngine::Components::Entity\fP"
.br
.RI "游戏实体 "
.ti -1c
.RI "class \fBEasyEngine::Components::Control\fP"
.br
.RI "控件 "
.ti -1c
.RI "class \fBEasyEngine::Components::Font\fP"
.br
.RI "字体 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBEasyEngine\fP"
.br
.RI "引擎 "
.ti -1c
.RI "namespace \fBComponents\fP"
.br
.RI "组件库 "
.in -1c
.SH "详细描述"
.PP 
组件库 

定义引擎下使用到的所有组件，包含：精灵、动画、对象、碰撞体等

.PP
\fB版权所有\fP
.RS 4
Copyright © 2025 CatIsNotFound 
.RE
.PP
\fB作者\fP
.RS 4
CatIsNotFound 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
