.TH "EasyEngine::Layer" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Layer \- 图层  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Scene\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBLayer\fP (const std::string &name)"
.br
.in -1c
.SH "详细描述"
.PP 
图层 

定义单个图层，在该图层下绘制元素 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
