.TH "EasyEngine::EventSystem" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::EventSystem \- 事件系统  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static bool \fBhandler\fP ()"
.br
.RI "事件处理器 "
.in -1c
.SS "友元"

.in +1c
.ti -1c
.RI "class \fBEngine\fP"
.br
.in -1c
.SH "详细描述"
.PP 
事件系统 
.SH "成员函数说明"
.PP 
.SS "bool EasyEngine::EventSystem::handler ()\fR [static]\fP"

.PP
事件处理器 所有事件都将被管理与处理

.PP
\fB返回\fP
.RS 4
返回 true 将持续处理事件，false 将结束处理事件 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
