.TH "EasyEngine::Size" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Size \- 尺寸、大小  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBSize\fP (float width, float height)"
.br
.ti -1c
.RI "void \fBreset\fP (float width, float height)"
.br
.RI "重新设置新的尺寸 "
.ti -1c
.RI "void \fBreset\fP (const \fBSize\fP &size)"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator+\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator\-\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator*\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator*\fP (float v) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator/\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator/\fP (float v) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (float v)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (float v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBSize\fP &s) const"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SH "详细描述"
.PP 
尺寸、大小 

用于调整对象的尺寸、大小 
.SH "成员函数说明"
.PP 
.SS "void EasyEngine::Size::reset (float width, float height)"

.PP
重新设置新的尺寸 
.PP
\fB参数\fP
.RS 4
\fIwidth\fP 
.br
\fIheight\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
