.TH "EasyEngine::Graphics::Point" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Graphics::Point \- 圆点  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBPoint\fP (\fBVector2\fP pos, SColor color=StdColor::Black)"
.br
.ti -1c
.RI "\fBPoint\fP (float x, float y, SColor color=StdColor::Black)"
.br
.ti -1c
.RI "\fBPoint\fP (float x, float y, uint8_t r, uint8_t g, uint8_t b, uint8_t a=255)"
.br
.ti -1c
.RI "\fBPoint\fP (\fBVector2\fP pos, const std::string &hex_color='#000000')"
.br
.ti -1c
.RI "\fBPoint\fP (float x, float y, const std::string &hex_color='#000000')"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBVector2\fP \fBpos\fP"
.br
.ti -1c
.RI "SColor \fBcolor\fP"
.br
.in -1c
.SH "详细描述"
.PP 
圆点 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
