.TH "EasyEngine::Components::Entity" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Components::Entity \- 游戏实体  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBEntity\fP (const std::string &\fBname\fP)"
.br
.RI "创建一个游戏实体 "
.ti -1c
.RI "\fBEntity\fP (const std::string &\fBname\fP, const \fBSprite\fP &sprite)"
.br
.ti -1c
.RI "\fBEntity\fP (const std::string &\fBname\fP, const \fBSpriteGroup\fP &group)"
.br
.ti -1c
.RI "\fBEntity\fP (const std::string &\fBname\fP, const \fBAnimation\fP &animation)"
.br
.ti -1c
.RI "\fBEntity\fP (const std::string &\fBname\fP, const \fBSprite\fP &sprite, const \fBGeometryF\fP &clip)"
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &\fBname\fP)"
.br
.RI "设置实体名称 "
.ti -1c
.RI "std::string \fBname\fP () const"
.br
.RI "获取实体名称 "
.ti -1c
.RI "void \fBsetColliderSelf\fP (const \fBGraphics::Rectangle\fP &rect)"
.br
.RI "设置碰撞器本身形状 "
.ti -1c
.RI "void \fBsetColliderSelf\fP (const \fBGraphics::Ellipse\fP &ellipse)"
.br
.RI "设置碰撞器本身形状 "
.ti -1c
.RI "void \fBsetColliderSelf\fP (const \fBGraphics::Point\fP &point)"
.br
.RI "设置碰撞器本身形状 "
.ti -1c
.RI "void \fBsetPosition\fP (\fBVector2\fP pos)"
.br
.RI "设置实体在窗口中所在的位置 "
.ti -1c
.RI "void \fBsetPosition\fP (float x, float y)"
.br
.RI "设置实体在窗口中所在的位置 "
.ti -1c
.RI "void \fBsetCenterPosition\fP (\fBVector2\fP pos)"
.br
.RI "设置实体的中心点 "
.ti -1c
.RI "void \fBsetCenterPosition\fP (float x, float y)"
.br
.RI "设置实体的中心点 "
.ti -1c
.RI "\fBVector2\fP \fBposition\fP () const"
.br
.RI "获取对象位于窗口的坐标 "
.ti -1c
.RI "\fBVector2\fP \fBcenterPosition\fP () const"
.br
.RI "获取对象的中心点 "
.ti -1c
.RI "\fBCollider\fP * \fBcollider\fP () const"
.br
.RI "获取实体碰撞器 "
.ti -1c
.RI "template<class Type> Type * \fBself\fP () const"
.br
.RI "获取实体本身 "
.ti -1c
.RI "const std::type_info & \fBtypeInfo\fP () const"
.br
.RI "获取当前实体的类型 "
.ti -1c
.RI "void \fBupdate\fP () const"
.br
.in -1c
.SS "友元"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.in -1c
.SH "详细描述"
.PP 
游戏实体 

用于作为游戏中的实体 
.SH "构造及析构函数说明"
.PP 
.SS "EasyEngine::Components::Entity::Entity (const std::string & name)\fR [explicit]\fP"

.PP
创建一个游戏实体 
.PP
\fB参数\fP
.RS 4
\fIname\fP 指定实体名称 
.RE
.PP

.SH "成员函数说明"
.PP 
.SS "template<class Type> Type * EasyEngine::Components::Entity::self () const"

.PP
获取实体本身 获取游戏实体的本体

.PP
\fB模板参数\fP
.RS 4
\fIType\fP 指定实体类型 
.RE
.PP
\fB返回\fP
.RS 4
返回对应类型的本体 
.RE
.PP
\fB注解\fP
.RS 4
目前支持的类：Sprite、SpriteGroup、Animation、GeometryF 

.PP
可通过使用 \fBtypeInfo()\fP 判断当前本体的类型 
.RE
.PP
\fB参见\fP
.RS 4
\fBtypeInfo\fP
.RE
.PP
\fB模板参数\fP
.RS 4
\fIType\fP 指定类型 
.RE
.PP
\fB返回\fP
.RS 4
返回指定类型的本体 
.RE
.PP
\fB注解\fP
.RS 4
可支持的类：Sprite、SpriteGroup、Animation、GeometryF 
.RE
.PP
\fB警告\fP
.RS 4
若指定的类型与现有本体的类型不一致，将强制报错并退出！ 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setCenterPosition (float x, float y)"

.PP
设置实体的中心点 
.PP
\fB参数\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setCenterPosition (\fBEasyEngine::Vector2\fP pos)"

.PP
设置实体的中心点 
.PP
\fB参数\fP
.RS 4
\fIpos\fP 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setColliderSelf (const \fBGraphics::Ellipse\fP & ellipse)"

.PP
设置碰撞器本身形状 
.PP
\fB参数\fP
.RS 4
\fIellipse\fP 指定椭圆 
.RE
.PP
\fB注解\fP
.RS 4
使用此函数后将自动按照实体调整大小及位置并自动启用碰撞器 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setColliderSelf (const \fBGraphics::Point\fP & point)"

.PP
设置碰撞器本身形状 
.PP
\fB参数\fP
.RS 4
\fIpoint\fP 指定圆点 
.RE
.PP
\fB注解\fP
.RS 4
使用此函数后将自动按照实体调整大小及位置并自动启用碰撞器 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setColliderSelf (const \fBGraphics::Rectangle\fP & rect)"

.PP
设置碰撞器本身形状 
.PP
\fB参数\fP
.RS 4
\fIrect\fP 指定矩形 
.RE
.PP
\fB注解\fP
.RS 4
使用此函数后将自动按照实体调整大小及位置并自动启用碰撞器 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setName (const std::string & name)"

.PP
设置实体名称 
.PP
\fB参数\fP
.RS 4
\fIname\fP 新的实体名称 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setPosition (float x, float y)"

.PP
设置实体在窗口中所在的位置 
.PP
\fB参数\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP

.SS "void EasyEngine::Components::Entity::setPosition (\fBEasyEngine::Vector2\fP pos)"

.PP
设置实体在窗口中所在的位置 
.PP
\fB参数\fP
.RS 4
\fIpos\fP 
.RE
.PP

.SS "const std::type_info & EasyEngine::Components::Entity::typeInfo () const"

.PP
获取当前实体的类型 
.PP
\fB返回\fP
.RS 4
返回一个类型信息，可用于 \fBself()\fP 上获取本体 
.RE
.PP
\fB注解\fP
.RS 4
对于未存放本体的游戏实体，将返回 void 类型 
.RE
.PP
\fB参见\fP
.RS 4
\fBself\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
