.TH "EasyEngine::SceneManager::Property" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::SceneManager::Property \- 场景属性  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Scene\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBComponents::Scene\fP > \fBscene\fP {}"
.br
.RI "场景 "
.ti -1c
.RI "std::function< void()> \fBenter_scene_event\fP {}"
.br
.ti -1c
.RI "uint32_t \fBenter_delay\fP {0}"
.br
.ti -1c
.RI "std::function< void()> \fBleave_scene_event\fP {}"
.br
.ti -1c
.RI "uint32_t \fBleave_delay\fP {0}"
.br
.in -1c
.SH "详细描述"
.PP 
场景属性 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
