.TH "EasyEngine::GeometryF" 3 "Version 1.0.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::GeometryF \- 位置、大小  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "void \fBreset\fP (const \fBVector2\fP &pos, const \fBSize\fP &size)"
.br
.ti -1c
.RI "void \fBreset\fP (float x, float y, float width, float height)"
.br
.ti -1c
.RI "void \fBresetPos\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "void \fBresetSize\fP (const \fBSize\fP &size)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBVector2\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBSize\fP \fBsize\fP"
.br
.in -1c
.SH "详细描述"
.PP 
位置、大小 

针对于 \fBVector2\fP 和 \fBSize\fP 组成，用于调整位置、大小 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
