.TH "EasyEngine" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine \- 引擎  

.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBAlgorithm\fP"
.br
.RI "算法库 "
.ti -1c
.RI "class \fBAudioSystem\fP"
.br
.RI "音频系统 "
.ti -1c
.RI "class \fBCursor\fP"
.br
.RI "鼠标光标 "
.ti -1c
.RI "class \fBEngine\fP"
.br
.RI "引擎类 "
.ti -1c
.RI "class \fBEventSystem\fP"
.br
.RI "事件系统 "
.ti -1c
.RI "struct \fBGeometry\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "struct \fBGeometryF\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "class \fBPainter\fP"
.br
.RI "图形绘制器 "
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "游戏资源 "
.ti -1c
.RI "struct \fBSize\fP"
.br
.RI "尺寸、大小 "
.ti -1c
.RI "struct \fBVector2\fP"
.br
.RI "向量坐标 "
.ti -1c
.RI "class \fBWindow\fP"
.br
.RI "窗口类 "
.in -1c
.SH "详细描述"
.PP 
引擎 

几乎包含所有引擎相关的类和命名空间。 通过使用 \fRusing namespace \fBEasyEngine\fP;\fP 可直接使用引擎里的一切东西 
.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
