.TH "EasyEngine::Components::Collider::Container::Shape" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Components::Collider::Container::Shape
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBGraphics::Rectangle\fP \fBrectangle\fP"
.br
.RI "矩形 1 "
.ti -1c
.RI "\fBGraphics::Ellipse\fP \fBellipse\fP"
.br
.RI "椭圆 2 "
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
