.TH "EasyEngine::Graphics::Ellipse" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Graphics::Ellipse \- 椭圆  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBEllipse\fP (\fBVector2\fP pos, \fBSize\fP area, SColor foreground=StdColor::Black, bool bordered_mode=true, bool filled_mode=false, SColor background=StdColor::Black)"
.br
.ti -1c
.RI "\fBEllipse\fP (float x, float y, float width, float height, SColor foreground=StdColor::Black, bool bordered_mode=true, bool filled_mode=false, SColor background=StdColor::Black)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBVector2\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBSize\fP \fBarea\fP"
.br
.ti -1c
.RI "bool \fBbordered_mode\fP"
.br
.ti -1c
.RI "bool \fBfilled_mode\fP"
.br
.ti -1c
.RI "SColor \fBfore_color\fP"
.br
.ti -1c
.RI "SColor \fBback_color\fP"
.br
.in -1c
.SH "详细描述"
.PP 
椭圆 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
