.TH "EasyEngine::Components::Element" 3 "Version 1.0.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Components::Element \- 存储元素  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.SS "友元"

.in +1c
.ti -1c
.RI "class \fBEntity\fP"
.br
.ti -1c
.RI "class \fBControl\fP"
.br
.in -1c
.SH "详细描述"
.PP 
存储元素 

用于存储 \fBSprite\fP, \fBAnimation\fP, \fBSpriteGroup\fP, ClipSprite 等 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
