.TH "EasyEngine::Vector2" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Vector2 \- 向量坐标  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBVector2\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBreset\fP (float x, float y)"
.br
.RI "重新设置新的向量 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "详细描述"
.PP 
向量坐标 

用于指定某对象的位置 
.SH "成员函数说明"
.PP 
.SS "void EasyEngine::Vector2::reset (float x, float y)"

.PP
重新设置新的向量 
.PP
\fB参数\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
