.TH "EasyEngine::Cursor::UserCustom::HotPoint" 3 "Version 1.0.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Cursor::UserCustom::HotPoint \- 用于定义鼠标光标的热点坐标  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "详细描述"
.PP 
用于定义鼠标光标的热点坐标 

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
