.TH "EasyEngine::Components::Control::Container::Self" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Components::Control::Container::Self
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBSprite\fP > \fBsprite\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBSpriteGroup\fP > \fBsprite_group\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBAnimation\fP > \fBanimation\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
