.TH "EasyEngine::Components::BGM" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EasyEngine::Components::BGM \- 背景音乐  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBBGM\fP (const std::string &resource_name)"
.br
.RI "从资源系统中指定资源并创建 \fBBGM\fP "
.ti -1c
.RI "void \fBsetPath\fP (const std::string &\fBpath\fP)"
.br
.RI "设置 \fBBGM\fP 播放源路径 "
.ti -1c
.RI "const std::string & \fBpath\fP () const"
.br
.RI "获取该 \fBBGM\fP 下的播放源路径 "
.ti -1c
.RI "void \fBplay\fP (bool loop=true)"
.br
.RI "播放 \fBBGM\fP "
.ti -1c
.RI "void \fBstop\fP ()"
.br
.RI "停止播放 \fBBGM\fP "
.ti -1c
.RI "void \fBpause\fP ()"
.br
.RI "暂停播放当前 \fBBGM\fP "
.ti -1c
.RI "bool \fBisPlayed\fP () const"
.br
.RI "当前是否正在播放 \fBBGM\fP "
.ti -1c
.RI "bool \fBisLoop\fP () const"
.br
.RI "当前是否正在循环播放 \fBBGM\fP "
.ti -1c
.RI "int64_t \fBposition\fP () const"
.br
.RI "获取播放进度 "
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "void \fBreload\fP ()"
.br
.in -1c
.SS "友元"

.in +1c
.ti -1c
.RI "class \fBAudioSystem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
背景音乐 
.SH "构造及析构函数说明"
.PP 
.SS "EasyEngine::Components::BGM::BGM (const std::string & resource_name)"

.PP
从资源系统中指定资源并创建 \fBBGM\fP 
.PP
\fB参数\fP
.RS 4
\fIresource_name\fP 指定资源名称 
.RE
.PP
\fB参见\fP
.RS 4
\fBResourceSystem\fP 
.RE
.PP

.SH "成员函数说明"
.PP 
.SS "bool EasyEngine::Components::BGM::isLoop () const"

.PP
当前是否正在循环播放 \fBBGM\fP 
.PP
\fB参见\fP
.RS 4
\fBstop\fP 

.PP
paused 

.PP
\fBisPlayed\fP 

.PP
\fBisLoop\fP 
.RE
.PP

.SS "bool EasyEngine::Components::BGM::isPlayed () const"

.PP
当前是否正在播放 \fBBGM\fP 
.PP
\fB参见\fP
.RS 4
\fBplay\fP 

.PP
\fBstop\fP 

.PP
paused 

.PP
\fBisLoop\fP 
.RE
.PP

.SS "void EasyEngine::Components::BGM::pause ()"

.PP
暂停播放当前 \fBBGM\fP 
.PP
\fB参见\fP
.RS 4
\fBplay\fP 

.PP
\fBstop\fP 

.PP
\fBisPlayed\fP 

.PP
\fBisLoop\fP 
.RE
.PP

.SS "void EasyEngine::Components::BGM::play (bool loop = \fRtrue\fP)"

.PP
播放 \fBBGM\fP 
.PP
\fB参数\fP
.RS 4
\fIloop\fP 是否循环播放（默认循环） 
.RE
.PP
\fB参见\fP
.RS 4
\fBstop\fP 

.PP
paused 

.PP
\fBisPlayed\fP 

.PP
\fBisLoop\fP 
.RE
.PP

.SS "int64_t EasyEngine::Components::BGM::position () const"

.PP
获取播放进度 
.PP
\fB返回\fP
.RS 4
返回一个以毫秒单位的播放时长 
.RE
.PP

.SS "void EasyEngine::Components::BGM::setPath (const std::string & path)"

.PP
设置 \fBBGM\fP 播放源路径 
.PP
\fB参数\fP
.RS 4
\fIpath\fP 指定路径 
.RE
.PP

.SS "void EasyEngine::Components::BGM::stop ()"

.PP
停止播放 \fBBGM\fP 
.PP
\fB参见\fP
.RS 4
\fBplay\fP 

.PP
paused 

.PP
\fBisPlayed\fP 

.PP
\fBisLoop\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
