.TH "is_serializable< T, std::void_t< decltype(std::declval< T >().serialize(std::declval< std::ofstream & >()))> >" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_serializable< T, std::void_t< decltype(std::declval< T >().serialize(std::declval< std::ofstream & >()))> >
.SH SYNOPSIS
.br
.PP
.PP
继承自 std::false_type , 以及 std::conditional_t< std::is_base_of_v< Serializable, T >, std::true_type, std::false_type > \&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
