.TH "D:/Coding/EasyEngine/src/preinclude.h" 3 "Version 0.1.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/EasyEngine/src/preinclude.h \- 预定义文件  

.SH SYNOPSIS
.br
.PP
\fR#include <SDL3/SDL\&.h>\fP
.br
\fR#include <SDL3_image/SDL_image\&.h>\fP
.br
\fR#include <SDL3_ttf/SDL_ttf\&.h>\fP
.br
\fR#include <SDL3_mixer/SDL_mixer\&.h>\fP
.br
\fR#include <fmt/core\&.h>\fP
.br
\fR#include 'libs/sdl3_gfx/SDL3_framerate\&.h'\fP
.br
\fR#include 'libs/sdl3_gfx/SDL3_gfxPrimitives\&.h'\fP
.br
\fR#include 'libs/sdl3_gfx/SDL3_gfxPrimitives_font\&.h'\fP
.br
\fR#include 'libs/sdl3_gfx/SDL3_imageFilter\&.h'\fP
.br
\fR#include 'libs/sdl3_gfx/SDL3_rotozoom\&.h'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <array>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <map>\fP
.br
\fR#include <tuple>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <typeindex>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <chrono>\fP
.br

.SH "详细描述"
.PP 
预定义文件 

预编译头文件，集中包含第三方库和标准库依赖，简化其他文件的引用。

.PP
\fB注解\fP
.RS 4
依赖 SDL3、SDL3_image、SDL3_mixer、SDL3_ttf 等第三方库 
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright © 2025 CatIsNotFound
.RE
.PP
\fB作者\fP
.RS 4
CatIsNotFound 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1\&.1-beta 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
