.TH "D:/Coding/EasyEngine/src/Resources.h" 3 "Version 1.0.1-beta" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/EasyEngine/src/Resources.h \- 资源管理  

.SH SYNOPSIS
.br
.PP
\fR#include 'Basic\&.h'\fP
.br
\fR#include 'Core\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBEasyEngine::FileSystem\fP"
.br
.RI "文件系统 "
.ti -1c
.RI "struct \fBEasyEngine::Resource\fP"
.br
.RI "资源 "
.ti -1c
.RI "class \fBEasyEngine::ResourceSystem\fP"
.br
.RI "资源系统 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBEasyEngine\fP"
.br
.RI "引擎 "
.in -1c
.SH "详细描述"
.PP 
资源管理 

包含资源系统、文件系统的用于管理资源的主要模块 
.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
