.TH "StdAudioSpec" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdAudioSpec \- 标准音频格式  

.SH SYNOPSIS
.br
.PP
.SH "详细描述"
.PP 
标准音频格式 

包含了不同级别的配置，可满足不同需求。 
.PP
\fB注解\fP
.RS 4
不是所有的配置都能适用于你的音频设备中， 

.PP
请根据实际的音频设备，设置适合的音频格式！ 
.RE
.PP
\fB参见\fP
.RS 4
\fBCore\&.h\fP 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
