.TH "Transition" 3 "Version 1.1.0-alpha" "Easy Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transition \- 场景过渡效果  

.SH SYNOPSIS
.br
.PP
.SH "详细描述"
.PP 
场景过渡效果 

包含了几种基本的用于场景过渡的效果 
.PP
\fB注解\fP
.RS 4
与早期测试版本定义方式不同，这里将命名为 \fR\fBTransition\fP\fP 作为命名空间，而非单独的抽象类！ 
.RE
.PP
\fB自从\fP
.RS 4
v1\&.1\&.0-alpha 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 Easy Engine 的 源代码自动生成\&.
